version: "3"
networks:
  petio-network:
    driver: bridge
services:
  petio:
    image: ghcr.io/petio-team/petio:latest
    container_name: "petio"
    hostname: petio
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    ports:
      - "7777:7777"
    networks:
      - petio-network
    volumes:
      - ./config:/app/api/config

  mongo:
    image: mongo:latest
    container_name: "mongo"
    hostname: mongo
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    ports:
      - "27017:27017"
    networks:
      - petio-network
    volumes:
      - ./db:/data/db
volumes:
  mongo-data:
    driver: local
