version: "3"
networks:
  mern-app:
    driver: bridge
services:
  petio:
    image: ghcr.io/petio-team/petio:latest
    container_name: "petio"
    ports:
      - "7777:7777"
    networks:
      - mern-app
    volumes:
      - ./config:/app/api/config

  mongo:
    image: mongo:latest
    container_name: "mongo"
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - ./db:/data/db
volumes:
  mongo-data:
    driver: local
