name: Binary - Admin

on:
  push:
    branches:
      - master

jobs:
  api-binary:
    name: Build Admin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
        working-directory: admin
      - name: Run build package
        run: npm run build
        env:
          CI: false
        working-directory: admin
      - uses: actions/upload-artifact@v2
        with:
          name: admin
          path: admin/dist/