name: Binary - API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  api-binary:
    name: Run Migrations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install packages
        run: npm ci
        working-directory: api
      - name: Run Migrations on Dev
        run: pkg . --out-path ./bin
        working-directory: api
      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: api/bin/