name: Docker Build

on:
  push:
    branches:
      - master
jobs:
  docker-front:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ghcr.io/ashdyson/petio-master:fe-latest -t ghcr.io/ashdyson/petio-master:fe-${GITHUB_SHA::8} .
      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login -u ashdyson --password-stdin ghcr.io
      - name: Push docker image
        run: docker push ghcr.io/ashdyson/petio-master:fe-latest
  docker-back:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: cd api && docker build -t ghcr.io/ashdyson/petio-master:be-latest -t ghcr.io/ashdyson/petio-master:be-${GITHUB_SHA::8} .
      - name: Docker login
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login -u ashdyson --password-stdin ghcr.io
      - name: Push docker image
        run: docker push ghcr.io/ashdyson/petio-master:be-latest
